### ISSUE TITLE
Nesting does not handle additional added stacks once created.

### ISSUE THREAD

**Issue by ajohnstone** [sparkleformation/sfn#118]
Please see the following for an example.

https://gist.github.com/ajohnstone/7eac18b2002b8f0fea94

If I do ```DEBUG=1 bundle exec sfn print``` it correctly prints all stacks. 

I would expect sfn update to add the new nested cloudformation stack. Additionally I've tried both shallow and deep nesting.

$ bundle  | egrep 'sparkle|sfn'
Using sparkle_formation 2.1.2
Using sfn 2.1.0
Using sfn-parameters 0.1.2
Using sfn-serverspec 0.1.4

**Comment by chrisroberts** [comment]
Hi! This is the expected behavior of an update. The update command you ran is only updating the existing stack which allows for parameter based updates. Because the updated template was not provided, no resources will be added/removed outside of run time resource changes based on parameters modifications. This is identified in the update output here:

> [Sfn]:   -> Name: photobox-services-test (no template update)

Because you are making modifications to your templates, you need to provide that by including the `--file root` flag. This will process the templates and apply them to your update. So the command you would want to run would be:

```
$ sfn update photobox-services-test --file root
```

Let me know if you still have any issues.

Cheers!

**Comment by ajohnstone** [comment]
@chrisroberts Thanks for that, really appreciate the quick response.
