### ISSUE TITLE
Apply stack flag doesn't pass compile time parameters

### ISSUE THREAD

**Issue by jimcroft** [sparkleformation/sfn#130]
Not sure if this is an issue/bug or design choice but using --apply-stack doesn't seem to apply compile time parameters as it does for runtime parameters.

**Comment by chrisroberts** [comment]
Yes, that is a design choice. Mainly due to the fact that "compile time parameters should never be used, unless you need to use them.". I doubt that apply-stack style behavior would ever be built in to sfn directly, as I feel it would encourage broader use of compile time parameters where they are not necessary. However, I am interested in your use case (which may provide some support for implementing a callback to provide this type of behavior in an "opt-in" context). Is it something you can share?

**Comment by jimcroft** [comment]
Ah ok, no problem. This isn't a blocker, just noticed the behaviour and wondered if it was expected.

The only compile time params I'm currently using are around CIDR subnet computation for new VPCs. eg. I have the following in my VPC template:

```
  cidr_block = IPAddress.parse(state!(:cidr_block))
  subnets = cidr_block.subnet(state!(:subnet_size))
  availability_zones = state!(:availability_zones)
```

and there's logic in the template to setup VPC subnets, routing tables, etc. I don't think I'll need compile time params in any other templates.

**Comment by chrisroberts** [comment]
:+1: If you do end up in a more complex situation where apply-stack functionality seems like it should be available, please let me know. I'm not fully opposed to making the behavior available through something like callbacks, but I haven't yet found a compelling reason to do so. Thanks for the feedback!
