### ISSUE TITLE
sfn stack create fails without useful human readable output

### ISSUE THREAD

**Issue by JonathanSerafini** [sparkleformation/sfn#6]
sfn stack create may fail with the following error when CAPABILITIES_IAM are not set : ERROR: Miasma::Error::ApiError::RequestError: Bad Request

Miasma itself appears to return the error, however it is squashed. 

Testable with the following patch : 
```
diff --git a/lib/sfn/command/create.rb b/lib/sfn/command/create.rb
index 531140d..c669b29 100644
--- a/lib/sfn/command/create.rb
+++ b/lib/sfn/command/create.rb
@@ -66,7 +66,13 @@ module Sfn
           stack.parameters = config[:parameters]

           stack.template = translate_template(stack.template)
-          stack.save
+          begin
+            stack.save
+          rescue StandardError => e
+            _debug(e)
+            raise e
+          end

         end

```

**Comment by chrisroberts** [comment]
I noticed this and it's been hanging out in my backlog of things "annoying things to fix". Since it's annoying someone else, I'll get a fix in place. It happened during the knife-cloudformation -> sfn conversion. The extracted error from the API call should be within the caught exception, and it was being displayed previously, but I believe it required a direct `.message` request on the exception. I'll see if I can get it updated today.

**Comment by chrisroberts** [comment]
This commit should fix things up:

https://github.com/spox/bogo-cli/commit/dc7f6c3cae3926f2df83514a78ceb1085d865005

Will get this pushed out shortly.

**Comment by chrisroberts** [comment]
Upgrading to 0.3.6 will automatically pull that supporting library update. Thanks for reporting this!
